# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('nick_name', models.CharField(max_length=40)),
                ('code_name', models.CharField(max_length=40)),
                ('superpower', models.CharField(max_length=50)),
                ('telephone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
    ]
