# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSuperPowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SuperPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='superpower',
        ),
        migrations.AddField(
            model_name='contactsuperpowers',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='contactsuperpowers',
            name='super_power',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.SuperPower'),
        ),
    ]
