# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 21:44
from __future__ import unicode_literals

from django.db import migrations, models


def add_contacts(apps, schema_editor):
    Contact = apps.get_model('contacts', 'Contact')
    SuperPower = apps.get_model('contacts', 'SuperPower')
    ContactSuperPowers = apps.get_model('contacts', 'ContactSuperPowers')

    super_powers = [
        'telepathy', 'astral projection', 'mind control', 'illusion casting',
        'memory manipulation', 'psychic blasts', 'sensing the presence of nearby mutants',
        'telekinesis', 'projects beam of concussive force from eyes', 'invisibility in shadows',
        'night-vision', 'wall crawling', 'line-of-sight teleportation', 'healing factor',
        'enhanced senses', 'retractable bone claws', 'adamantium-bonded skeleton',
        'absorbs powers by skin-to-skin touch',
        'absorbs powers permenantly by prolonged skin-to-skin contact',
        'manipulating metal', 'flight', 'electro-magnetic radiation',
        'change inanimate objects', 'enhanced agility', 'hypnotic charm',
        'shape-shifting', 'reactive abilities', 'weather manipulation'
    ]

    for super_power in super_powers:
        SuperPower(power=super_power).save()

    contacts_to_create = [(
        'Charles Francis', 'Xavier', None, 'Professor X', '011-111-1122', 'prof_x@sgy.org', [
            'telepathy', 'astral projection', 'mind control', 'illusion casting',
            'memory manipulation', 'psychic blasts', 'sensing the presence of nearby mutants',
        ]), (
        'Scott', 'Summers', None, 'Cyclops', '011-111-2211', 'uno_eye@sgy.org', [
            'projects beam of concussive force from eyes'
        ]), (
        'Jean', 'Grey', None, 'Jean Grey', '011-112-2211', 'hot_for_scott@sgy.org', [
            'telekinesis', 'telepathy'
        ]), (
        'Anna', 'Marie', None, 'Rogue', '011-111-2211', 'uno_eye@sgy.org', [
            'absorbs powers by skin-to-skin touch',
            'absorbs powers permenantly by prolonged skin-to-skin contact'
        ]), (
        'Kurt', 'Wagner', None, 'NightCrawler', None, 'now_here_now_there@sgy.org', [
            'invisibility in shadows', 'night-vision', 'wall crawling',
            'line-of-sight teleportation'
        ]), (
        'James', 'Howlett', 'Logan', 'Wolverine', '011-111-2211', 'sharp_claws@sgy.org', [
            'healing factor', 'enhanced senses', 'retractable bone claws',
            'adamantium-bonded skeleton'
        ]), (
        'Ororo', 'Monroe', None, 'Storm', '022-111-2211', 'i_can_see_my_house_from_here@sgy.org', [
            'weather manipulation', 'flight'
        ]), (
        'Raven', 'Darkhölme', None, 'Mystique', '022-111-2211',
        'mighty-morphing-power-ranger@mut_bros.org', [
            'shape-shifting', 'healing factor', 'reactive abilities'
        ]), (
        'Max', 'Eisenhardt', 'Magnus', 'Magneto', '022-111-2211', 'metal_me@mut_bros.org', [
            'manipulating metal', 'flight', 'electro-magnetic radiation'
        ]), (
        'Rémy', 'LeBeau', None, 'Gambit', None, 'card_up_my_sleeve@sgy.org', [
            'change inanimate objects', 'enhanced agility', 'hypnotic charm'
        ])]

    for contact_details in contacts_to_create:
        first_name, last_name, nick_name, code_name, telephone_number, email, powers = \
            contact_details

        contact = Contact(
            first_name=first_name, last_name=last_name, nick_name=nick_name, code_name=code_name,
            telephone_number=telephone_number, email=email)
        contact.save()

        for power in powers:
            ContactSuperPowers(
                contact=contact, super_power=SuperPower.objects.get(power=power)).save()


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20160206_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='nick_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.RunPython(add_contacts)
    ]
