# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20160207_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='avatar',
            new_name='profile_picture',
        ),
    ]
