# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 09:54
from __future__ import unicode_literals

import os

from django.conf import settings
from django.db import migrations
from django.core.files import File


def add_avatars(apps, schema_editor):
    Contact = apps.get_model('contacts', 'Contact')
    Avatar = apps.get_model('avatar', 'Avatar')

    png_avatars = ['mystique', 'rogue']
    for contact in Contact.objects.all():
        avatar_source_path = os.path.join(
            settings.BASE_DIR, 'addressbook', 'site_media', 'static', 'images', 'source')
        code_name = contact.code_name.lower()
        avatar_filename = '{}.{}'.format(code_name, 'png' if code_name in png_avatars else 'jpg')

        contact_avatar = File(open('{}/{}'.format(avatar_source_path, avatar_filename), 'r'))
        Avatar(contact=contact, primary=True, avatar=contact_avatar).save()


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_remove_contact_profile_picture'),
    ]

    operations = [
        migrations.RunPython(add_avatars)
    ]
